# Dependency Auto-Update
# Checks for outdated npm dependencies weekly and creates a PR.
#
# Features:
# - Runs weekly (configurable)
# - Checks for outdated packages
# - Creates a PR with detailed update info
# - Separates major/minor/patch updates
# - Skips if no updates available
# - Manual trigger supported
#
# Usage: Copy to .github/workflows/deps.yml

name: Dependency Updates

on:
  schedule:
    - cron: '0 9 * * 1'  # Every Monday at 9:00 UTC
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  update-deps:
    name: Check for updates
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Check for outdated packages
        id: outdated
        run: |
          npm install
          OUTDATED=$(npm outdated --json 2>/dev/null || true)

          if [ -z "$OUTDATED" ] || [ "$OUTDATED" = "{}" ]; then
            echo "has_updates=false" >> $GITHUB_OUTPUT
            echo "No outdated packages found."
            exit 0
          fi

          echo "has_updates=true" >> $GITHUB_OUTPUT
          echo "$OUTDATED" > /tmp/outdated.json

          # Count updates by type
          MAJOR=$(node -e "
            const d = require('/tmp/outdated.json');
            const count = Object.values(d).filter(p =>
              p.current && p.latest && p.current.split('.')[0] !== p.latest.split('.')[0]
            ).length;
            console.log(count);
          ")
          MINOR=$(node -e "
            const d = require('/tmp/outdated.json');
            const count = Object.values(d).filter(p =>
              p.current && p.latest &&
              p.current.split('.')[0] === p.latest.split('.')[0] &&
              p.current.split('.')[1] !== p.latest.split('.')[1]
            ).length;
            console.log(count);
          ")
          PATCH=$(node -e "
            const d = require('/tmp/outdated.json');
            const count = Object.values(d).filter(p =>
              p.current && p.latest &&
              p.current.split('.')[0] === p.latest.split('.')[0] &&
              p.current.split('.')[1] === p.latest.split('.')[1] &&
              p.current !== p.latest
            ).length;
            console.log(count);
          ")

          echo "major=$MAJOR" >> $GITHUB_OUTPUT
          echo "minor=$MINOR" >> $GITHUB_OUTPUT
          echo "patch=$PATCH" >> $GITHUB_OUTPUT

      - name: Update dependencies
        if: steps.outdated.outputs.has_updates == 'true'
        run: |
          # Update all to latest within semver range
          npm update

          # For major updates, list them but don't auto-install
          # (they may have breaking changes)

      - name: Generate PR body
        if: steps.outdated.outputs.has_updates == 'true'
        id: body
        run: |
          cat > /tmp/pr-body.md << 'BODY'
          ## Dependency Updates

          Automated dependency update check.

          BODY

          node -e "
            const d = require('/tmp/outdated.json');
            const lines = [];

            const major = [], minor = [], patch = [];
            for (const [name, info] of Object.entries(d)) {
              if (!info.current || !info.latest) continue;
              const entry = '| \`' + name + '\` | ' + info.current + ' | ' + info.latest + ' |';
              const [cMaj, cMin] = info.current.split('.');
              const [lMaj, lMin] = info.latest.split('.');
              if (cMaj !== lMaj) major.push(entry);
              else if (cMin !== lMin) minor.push(entry);
              else patch.push(entry);
            }

            if (major.length) {
              lines.push('### ⚠️ Major updates (may have breaking changes)');
              lines.push('| Package | Current | Latest |');
              lines.push('| --- | --- | --- |');
              lines.push(...major);
              lines.push('');
            }
            if (minor.length) {
              lines.push('### Minor updates');
              lines.push('| Package | Current | Latest |');
              lines.push('| --- | --- | --- |');
              lines.push(...minor);
              lines.push('');
            }
            if (patch.length) {
              lines.push('### Patch updates');
              lines.push('| Package | Current | Latest |');
              lines.push('| --- | --- | --- |');
              lines.push(...patch);
              lines.push('');
            }

            require('fs').appendFileSync('/tmp/pr-body.md', lines.join('\n'));
          "

          echo "---" >> /tmp/pr-body.md
          echo "*Auto-generated by dependency update workflow*" >> /tmp/pr-body.md

      - name: Create Pull Request
        if: steps.outdated.outputs.has_updates == 'true'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          BRANCH="deps/update-$(date +%Y%m%d)"
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          # Check if branch already exists
          if git ls-remote --heads origin "$BRANCH" | grep -q "$BRANCH"; then
            echo "Branch $BRANCH already exists. Skipping."
            exit 0
          fi

          git checkout -b "$BRANCH"
          git add -A
          git diff --cached --quiet && echo "No changes to commit" && exit 0

          MAJOR="${{ steps.outdated.outputs.major }}"
          MINOR="${{ steps.outdated.outputs.minor }}"
          PATCH="${{ steps.outdated.outputs.patch }}"

          git commit -m "chore(deps): update dependencies (${MAJOR} major, ${MINOR} minor, ${PATCH} patch)"
          git push origin "$BRANCH"

          gh pr create \
            --title "chore(deps): dependency updates $(date +%Y-%m-%d)" \
            --body-file /tmp/pr-body.md \
            --base main \
            --head "$BRANCH"
